# Generated by Django 4.2.7 on 2023-11-25 19:04

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to=shop.models.upload_to, verbose_name='Image'),
        ),
    ]
